### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by ProfessorVenkman** [Electron-Cash/Electron-Cash#2071]
Crash Report
============

This crash report was reported through the automatic crash reporting system 🤖

Traceback
--------------

```Python traceback
  File "electroncash/util.py", line 830, in run_with_except_hook
  File "electroncash/network.py", line 1503, in run
  File "electroncash/network.py", line 1476, in wait_on_sockets
  File "electroncash/network.py", line 892, in process_responses
  File "electroncash/network.py", line 793, in process_response
  File "electroncash/network.py", line 1545, in on_notify_header
  File "electroncash/network.py", line 1610, in request_initial_proof_and_headers
  File "electroncash/network.py", line 1564, in _process_latest_tip
  File "electroncash/blockchain.py", line 143, in can_connect
  File "electroncash/blockchain.py", line 586, in can_connect
  File "electroncash/blockchain.py", line 485, in get_bits
  File "electroncash/blockchain.py", line 447, in get_asert_anchor
  File "electroncash/blockchain.py", line 405, in get_median_time_past
  File "electroncash/blockchain.py", line 405, in <listcomp>

TypeError: 'NoneType' object is not subscriptable
```

Reporter
------------

This issue was reported by 4 user(s):

| Electron Cash Version  | Python Version | Operating System  | Wallet Type  | Locale |
|---|---|---|---|---|
| 4.2.0  | 3.6.9 (default, Oct 21 2020, 19:43:27)  [GCC Clang 10.0.1 ] | Darwin-19.6.0-x86_64-i386-64bit | standard |  | 
| 3.6.5  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard | en_NL | 
| 3.6.5  | 3.6.9 (default, Jun 28 2018, 19:01:02)  [GCC 5.4.0 20160609] | Linux-4.19.0-12-amd64-x86_64-with-debian-10.7 | slp_standard | en_US | 
| 3.6.5  | 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)] | Windows-10-10.0.18362-SP0 | standard | en_US | 

Additional Information
------------------------

The reporting user(s) did not provide additional information.

**Comment by gasull** [comment]
This happens because [`read_header` is returning `None`](https://github.com/Electron-Cash/Electron-Cash/blob/373e5a8f27fc266f4d23ecb3fb727911d9278d80/electroncash/blockchain.py#L365).  And it is doing it in several execution branches.

I started working on this and came with this fix:

```diff
diff --git a/electroncash/blockchain.py b/electroncash/blockchain.py
index 660ff0f01..468fa4a46 100644
--- a/electroncash/blockchain.py
+++ b/electroncash/blockchain.py
@@ -400,10 +400,15 @@ class Blockchain(util.PrintError):
     def get_median_time_past(self, height, chunk=None):
         if height < 0:
             return 0
-        times = [
-            self.read_header(h, chunk)['timestamp']
-            for h in range(max(0, height - 10), height + 1)
-        ]
+
+        times = []
+        for h in range(max(0, height - 10), height + 1):
+            header = self.read_header(h, chunk)
+            if header is None:
+                continue
+            times.append(header['version'])
+        if not times:
+            return 0
         return sorted(times)[len(times) // 2]
 
     def get_suitable_block_height(self, suitableheight, chunk=None):
```

But it's probably wrong because this might alter the values returned when calculating the EDA.

Where can I read more about the EDA?

Alternatively, maybe someone with more experience in this codebase can take it from here.

**Comment by cculianu** [comment]
This has been fixed already. It was because I brain farted in my assert implementation. It's fixed in 4.2.3.

**Comment by cculianu** [comment]
Oh wait -- your fix is unrelated. Hmm.

**Comment by cculianu** [comment]
Yeah your fix would lead to incorrect results... sadly.

This bug is related to the bug I fixed with ASERT.   In fact looking at the afflicted versions of EC, it most certainly is the same bug...


I am going to close this again because I'm like 87% sure it's the same bug.

**Comment by gasull** [comment]
I don't see how to reopen the bug, @cculianu.

This looks like a completely different bug to me, although I still don't know the codebase too well.

The [original crash report above](https://github.com/Electron-Cash/Electron-Cash/issues/2071#issue-749882284) shows that the error originates in the list comprehension that is assigned to `times`, and which calls `read_header`.

While your fix on 3f63318 is for `get_asert_anchor`.

Am I missing something?

(And yes, my code above is at most a starting point or a stub).

**Comment by cculianu** [comment]
> Am I missing something?

That whole codepath that scans for MTP should not be executed for blocks before the checkpoint.  With the new asert fixes in 3f633185eec10145eb52df20b2c1f4ae6bd9483d it won't be -- this you can't get `None` for non-existant headers.  

The fix makes it so you can never ask the wrong question of the wrong set of blocks to which there is no answer.
